<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1e6d3411-cb6b-4bcf-9d96-7cba6cdee075</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.12.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FiapCloudGames.Payments.Infrastructure\FiapCloudGames.Payments.Infrastructure.csproj" />
    <ProjectReference Include="..\FiapCloudGames.Payments.Observability\FiapCloudGames.Payments.Observability.csproj" />
    <ProjectReference Include="..\FiapCloudGames.Queue\FiapCloudGames.Queue.csproj" />
  </ItemGroup>

</Project>
